services:

  backoffice:
    build: ./backoffice
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: "YOUR API KEY"
    volumes:
      - ./backoffice:/backoffice
    networks:
      - backoffice
    depends_on:
      postgres:
        condition: service_healthy

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app
    networks:
      - backoffice
    depends_on:
      - backoffice

  postgres:
    image: pgvector/pgvector:pg18-trixie
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - backoffice
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    networks:
      - backoffice
    depends_on:
      postgres:
        condition: service_started

volumes:
  pgdata:

networks:
  backoffice:
    name: backoffice
    driver: bridge